# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30ecea76a45cf4d5ce2c24fc1deb145eff54f59b3bbc1cc35c543bffb5f9a29e76e8b45107e3e9894b3cdeb04391561bf2443b349080f683a514dc58649b60b

test:
  secret_key_base: ece6ce61b0cb43dc883a5e4e5f342e881d00cd83be382b07a47af7abe575b15747eba7e0bae610e6c4974f839ccb168f4ae1bb6753103705a239e0e157ca182e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
